services:
  - type: web
    name: cod-manager-backend
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
